intrinsic FindI(OBasis::SeqEnum, p::RngIntElt : Bound:=7, NumTries:=20000) -> BoolElt, .
{Finds i in the quaternion order with basis OBasis such that trd(i)=0 and -nrd(i) mod p is a non-square.
 Requires p != 2 for the odd prime branch.}
    ZZ := Integers();
    Zp := Integers(p);

    if p ne 2 then
        for _ in [1..NumTries] do
            coeffs := [Random([-Bound..Bound]) : _ in [1..4]];
            if coeffs eq [0,0,0,0] then continue; end if;
            x := &+[coeffs[k] * OBasis[k] : k in [1..4]];
            if (LegendreSymbol(ZZ!(Zp!(-Norm(x))), p) eq -1) and (Trace(x) eq 0) then
                return true, x;
            end if;
        end for;
    else
        for ele in OBasis do
            if (Trace(ele) eq 1) and ((ZZ!Norm(ele) mod 2) ne 0) then
                return true, ele;
            end if;
        end for;

        for _ in [1..NumTries] do
            coeffs := [Random([-Bound..Bound]) : _ in [1..4]];
            if coeffs eq [0,0,0,0] then continue; end if;
            x := &+[coeffs[k] * OBasis[k] : k in [1..4]];
            if (Trace(x) eq 1) and ((ZZ!Norm(x) mod 2) ne 0) then
                return true, x;
            end if;
        end for;
    end if;

    return false, "increase NumTries";
end intrinsic;


intrinsic FindJ(OBasis::SeqEnum, I::., p::RngIntElt : Bound:=7, NumTries:=20000) -> BoolElt, .
{Finds j in the quaternion order with basis OBasis such that v_p(nrd(j))=1, trd(ij)=0, trd(j)=0.}
    ZZ := Integers();
    M := Matrix(ZZ, 1, 4, [[Trace(OBasis[i] * I) : i in [1..4]]]);
    N := Nullspace(Transpose(M));
    NBasis := [&+[coeff[i] * OBasis[i] : i in [1..4]] : coeff in Basis(N)];
    for x in NBasis do
        if (Valuation(Norm(x), p) eq 1) and (Trace(x) eq 0) then
            return true, x;
        end if;
    end for;

    for _ in [1..NumTries] do
        coeffs := [Random([-Bound..Bound]) : _ in [1..3]];
        if coeffs eq [0,0,0] then continue; end if;
        x := &+[coeffs[k] * NBasis[k] : k in [1..3]];
        if (Valuation(Norm(x), p) eq 1) and (Trace(x) eq 0) then
            return true, x;
        end if;
    end for;

    return false, "increase Bound or NumTries";
end intrinsic;


intrinsic Findc(OBasis::SeqEnum, I::., p::RngIntElt) -> SeqEnum
{Finds c in O such that <c-bar> = F_(p^2)^x, returned as coordinates [c0, c1] with c = c0 + c1*I.}
    Fp := GF(p);
    P<x> := PolynomialRing(Fp);
    if p ne 2 then
        K<alpha> := ext<Fp | x^2 + Norm(I)>;
    else
        K<alpha> := ext<Fp | x^2 + Trace(I)*x + Norm(I)>;
    end if;
    assert Degree(K) eq 2;
    gen := Eltseq(PrimitiveElement(K));
    return gen;
end intrinsic;


intrinsic CoeffsInBasis(x::., I::., J::.) -> .
{Writes x as x = a + b*I + c*J + d*I*J and returns the coefficient row vector.}
    K := I*J;
    M := Matrix(Rationals(), [[1,0,0,0], Eltseq(I), Eltseq(J), Eltseq(K)]);
    return Solution(M, Matrix(Rationals(), [Eltseq(x)]));
end intrinsic;


intrinsic SubgroupGensInBasis(I::., J::., gens::SeqEnum) -> SeqEnum
{Returns gens expressed as coefficient row vectors in the basis [1, I, J, IJ].}
    return [CoeffsInBasis(gen, I, J) : gen in gens];
end intrinsic;


intrinsic BuildG(c::SeqEnum, i::., j::., p::RngIntElt, e::RngIntElt) -> ., ., .
{Builds the group G = (O/p^e O)^x together with matrices I, J representing i, j.}
    if p ne 2 then
        assert (Trace(i) eq 0) and (Trace(j) eq 0);
        Stilde := Integers(NumberField(Polynomial([Norm(i), 0, 1])));
        S := quo< Stilde | p^e>;
        GL2 := GL(2, S);
        I := Matrix([[S!Stilde.2, 0], [0, -S!Stilde.2]]);
    else
        Stilde := Integers(NumberField(Polynomial([Norm(i), -Trace(i), 1])));
        S := quo< Stilde | p^e>;
        GL2 := GL(2, S);
        I := Matrix([[S!Stilde.2, 0], [0, S!(Stilde.1 - Stilde.2)]]);
    end if;
    J := Matrix([[0, S!(-Norm(j))], [1, 0]]);
    c := c[1] + c[2] * I;
    m := 2*e - 1;
    return I, J, sub< GL2 | [c] cat [1+I*J^k : k in [1..m]] cat [1+J^k : k in [1..m]]>;
end intrinsic;


intrinsic BuildGSubgroup(I::., J::., G::., gens::SeqEnum) -> .
{Returns the subgroup of G generated by gens expressed in the basis [1, I, J, IJ].}
    K := I*J;
    H_gens := [coeff[1,1]+coeff[1,2]*I+coeff[1,3]*J+coeff[1,4]*K : coeff in gens];
    return sub < G | H_gens>;
end intrinsic;
